spring:
  application:
    name: todo

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      show-sql: true
      properties:
        hibernate.format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
      database: h2
